language: node_js
before_script:
  - git submodule update --init
  - npm install -g codeclimate-test-reporter
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - coveralls < coverage/lcov.info
  - scripts/travis-gh-pages
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9cab5fe0c9595511cd81
    on_success: change
    on_failure: always
    on_start: never
